# docker-compose.yml
version: "3.9"
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchises
      MYSQL_USER: franchise
      MYSQL_PASSWORD: franchise
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uapp", "-papp" ]
      interval: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: