spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true